update bitrise.yml and fix lint errors

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -18,15 +18,29 @@ workflows:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
     - git-clone@4: {}
     - cache-pull@2: {}
-    - script@1:
-        title: Do anything with Script step
     - certificate-and-profile-installer@1: {}
     - recreate-user-schemes@1:
         inputs:
         - project_path: $BITRISE_PROJECT_PATH
+    - swiftlint@0:
+        inputs:
+        - strict: 'yes'
+        - linting_path: "$BITRISE_SOURCE_DIR"
+    - script@1:
+        title: Fail on SwiftLint
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+
+            if [ -z "${SWIFTLINT_REPORT}" ]
+            then
+              echo "SwiftLint passed, nice!"
+            else
+              echo "SwiftLint failed, correct issues."
+              exit 1
+            fi
     - xcode-test@2:
         inputs:
-        - verbose: 'yes'
         - project_path: $BITRISE_PROJECT_PATH
         - scheme: $BITRISE_SCHEME
         - export_method: $BITRISE_EXPORT_METHOD
